## Exercise 1 (arrays & shape)

- Create a 1D array from 1 to 15
- Reshape it into a 3x5 matrix.
- Print:
    - The matrix
    - The shape
    - The second row
    - The last column
    - the first 2 rows, and 2 cols

In [4]:
import numpy as np
 
arr = np.arange(1,16)
 
matrix = arr.reshape(3, 5)
 
print("Matrix:")
print(matrix)
 
print("SHape: ")
print(matrix.shape)
 
print("Second row: ")
print(matrix[1])
 
print("Last colum:")
print(matrix[:, -1])
 
print("First 2 rows,2 column:")
print(matrix[:2, :2])

Matrix:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
SHape: 
(3, 5)
Second row: 
[ 6  7  8  9 10]
Last colum:
[ 5 10 15]
First 2 rows,2 column:
[[1 2]
 [6 7]]


#### Exercise 2 - Calculate Revenues
- you run a bakery and have taken record of sales everyday
- you created a table as such, for 3 quantities, [Cakes, Donuts, Muffins]
- here is the sales data for 6 days :
```python
[[10, 20, 15], # day 1
[23, 43, 55], # day 2
[23, 10, 22], # day 3
[76, 56, 82], # day 4
[23, 31, 27], # day 5
[18, 19, 15]] # day 6
```
1. create prices array for the three quantities: `[3.50, 2.00, 2.50]`
2. Calculate daily revenue for each day
3. Calculate the revenue for each of the items
4. Calculate the Net Gross (total) amount of sales



In [3]:
import numpy as np
price = np.array([3.50, 2.00, 2.50])
 
sales = np.array([[10, 20, 15], # day 1
                  [23, 43, 55], # day 2
                  [23, 10, 22], # day 3
                  [76, 56, 82], # day 4
                  [23, 31, 27], # day 5
                  [18, 19, 15]  # day 6
])
 
print("Welcome to Happy Bakery!")
print("="*30)
 
# Daily revenue
revenue_daily = sales.sum(axis = 1)
print(f"Daily Revenue") 
print(f"Day 1: ${revenue_daily[0]}")
print(f"Day 2: ${revenue_daily[1]}")
print(f"Day 3: ${revenue_daily[2]}")
print(f"Day 4: ${revenue_daily[3]}")
print(f"Day 5: ${revenue_daily[4]}")
print(f"Day 6: ${revenue_daily[5]}")

print("="*30)
 
# Revenue for each of the item
revenue_item = sales.sum(axis = 0)
print(f"Revenue per Item ")
print(f"Cakes: ${revenue_item[0]}")
print(f"Donuts: ${revenue_item[1]}")
print(f"Muffins: ${revenue_item[2]}")

print("="*30)
 
# Total sales
total_sales = sales.sum()
print(f"Total sales: ${total_sales}")

Welcome to Happy Bakery!
Daily Revenue
Day 1: $45
Day 2: $121
Day 3: $55
Day 4: $214
Day 5: $81
Day 6: $52
Revenue per Item 
Cakes: $173
Donuts: $179
Muffins: $216
Total sales: $568
